import "@/assets/css/globals.css";
import type { Metadata } from "next";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Inter, Cairo, Lora } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { DirectionProvider } from "@/components/ui/direction";
import { ReferenceDataProvider } from "@/providers/reference-data.provider";
import { http } from "@/lib/http";
import { ReferenceData } from "@/types/reference-data";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

const CairoFont = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic"],
  weight: ["400", "500", "700", "200"],
});

export const metadata: Metadata = {
  title: {
    default: "Huqouq",
    template: "Huqouq - %s",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    return notFound();
  }

  const dir = locale === "ar" ? "rtl" : "ltr";

  // Fetch the reference data from the API
  const { data, ok } = await http.get<ReferenceData>("/api/reference-data");

  if (!ok) {
    throw new Error("Failed to fetch reference data");
  }

  console.log(data);

  return (
    <html
      lang={locale}
      dir={dir}
      className={`${inter.variable} ${lora.variable} ${CairoFont.variable} h-full antialiased`}
    >
      <ReferenceDataProvider initialReferenceData={data}>
        <NuqsAdapter>
          <NextIntlClientProvider>
            <TooltipProvider>
              <DirectionProvider dir={dir}>
                <body className="min-h-full flex flex-col">
                  {children}
                  <Toaster richColors />
                </body>
              </DirectionProvider>
            </TooltipProvider>
          </NextIntlClientProvider>
        </NuqsAdapter>
      </ReferenceDataProvider>
    </html>
  );
}
